export const imageRequest = {
  enable_hr: false,
  prompt: "A portrait of a middle-aged man with short salt-and-pepper hair, a kraken tattoo on his left forearm, and a bandana tied around his head.",
  styles: [],
  seed: -1,
  subseed: -1,
  sampler_name: "DPM++ 2M",
  batch_size: 1,
  n_iter: 1,
  steps: 50,
  cfg_scale: 7,
  width: 512,
  height: 512,
  restore_faces: false,
  tiling: false,
  do_not_save_samples: false,
  do_not_save_grid: false,
  negative_prompt: "bad-hands-5, easynegative, bad face, melting face",
  s_noise: 1,
  override_settings_restore_afterwards: true,
  script_args: [],
  sampler_index: "DPM++ 2M",
  send_images: true,
  save_images: false
};