--liquibase formatted sql

--changeset Zachari.Barnes:5 labels:update-sessions context:update-sessions
--comment: "Updating the sessions table 11-20-23"
ALTER TABLE public.sessions ADD CONSTRAINT session_id UNIQUE (session_id);
--rollback ALTER TABLE public.sessions DROP CONSTRAINT session_id;

--changeset Zachari.Barnes:6 labels:create-usage context:create-usage
--comment: "Creating the usage table 11-20-23"
CREATE TABLE public.usage (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	user_id BIGINT NOT NULL,
	session_id text NOT NULL,
	prompt_tokens BIGINT NOT NULL DEFAULT 0,
	completion_tokens BIGINT NOT NULL DEFAULT 0,
	total_tokens BIGINT NOT NULL DEFAULT 0,
	cost numeric(15,5) NOT NULL DEFAULT 0,
	model text NOT NULL,
	character_id BIGINT NULL,
	created_date timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
	CONSTRAINT usage_pk PRIMARY KEY (id),
	CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES public.users (id),
	CONSTRAINT session_id_fk FOREIGN KEY (session_id) REFERENCES public.sessions (session_id),
	CONSTRAINT character_id_fk FOREIGN KEY (character_id) REFERENCES public.characters (id)
);
--rollback DROP TABLE public.usage;


--changeset Zachari.Barnes:7 labels:update-characters context:update-characters
--comment: "Updating the characters table 11-20-23"
ALTER TABLE public.characters ADD COLUMN likes numeric NOT NULL DEFAULT 0;
ALTER TABLE public.characters ADD COLUMN dislikes numeric NOT NULL DEFAULT 0;
ALTER TABLE public.characters ADD COLUMN reports numeric NOT NULL DEFAULT 0;
--rollback ALTER TABLE public.characters DROP COLUMN likes;
--rollback ALTER TABLE public.characters DROP COLUMN dislikes;
--rollback ALTER TABLE public.characters DROP COLUMN reports;

--end -8-11-23