--liquibase formatted sql

--changeset Zachari.Barnes:1 labels:create-users context:create-users
--comment: "Creating the users table"
CREATE TABLE public.users (
	id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username varchar(100) NULL,
	email varchar(320) NOT NULL,
	picture text NULL,
	subscriber boolean NOT NULL DEFAULT false,
	last_login timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
	created_date timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
	modified_date timestamp without time zone NOT NULL DEFAULT (now() at time zone 'utc'),
	CONSTRAINT users_pk PRIMARY KEY (id)
);
--rollback DROP TABLE public.users;


--changeset Zachari.Barnes:2 labels:create-session context:create-sessions
--comment: "Creating the session table -8-11-23"
CREATE TABLE public.sessions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	user_id BIGINT NOT NULL,
	session_id text NULL,
	expiration timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc')+ interval '6 hours',
	created_date timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
	modified_date timestamp without time zone NOT NULL DEFAULT (now() at time zone 'utc'),
	CONSTRAINT session_pk PRIMARY KEY (id),
	CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES public.users (id)
);
--rollback DROP TABLE public.sessions;


--changeset Zachari.Barnes:3 labels:create-characters context:create-characters
--comment: "Creating the characters table -8-11-23"
CREATE TABLE public.characters (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	user_id BIGINT NOT NULL,
	world text null,
	ruleset text null,
	character_name text null,
	image_url text null,
	portrait_prompt text null,
	appearance jsonb null,
	description text null,
	goals text null,
	quirks text null,
	backstory text null,
	items jsonb null,
	shop jsonb null,
	stat_block jsonb null,
	created_date timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
	modified_date timestamp without time zone NOT NULL DEFAULT (now() at time zone 'utc'),
	CONSTRAINT character_id PRIMARY KEY (id),
	CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES public.users (id)
);
--rollback DROP TABLE public.characters;

--end -8-11-23