--liquibase formatted sql

--changeset Zachari.Barnes:1 labels:create-users context:create-users
--comment: "Creating the users table"
CREATE TABLE public.users (
	id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username varchar(100) NULL,
	email varchar(320) NOT NULL,
	picture text NULL,
	subscriber boolean NOT NULL DEFAULT false,
	last_login timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
	created_date timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
	modified_date timestamp without time zone NOT NULL DEFAULT (now() at time zone 'utc'),
	CONSTRAINT users_pk PRIMARY KEY (id)
);
--rollback DROP TABLE public.users;

-- --changeset your.name:1 labels:example-label context:example-context
-- --comment: example comment
-- create table person (
--     id int primary key auto_increment not null,
--     name varchar(50) not null,
--     address1 varchar(50),
--     address2 varchar(50),
--     city varchar(30)
-- )
-- --rollback DROP TABLE person;

-- --changeset your.name:2 labels:example-label context:example-context
-- --comment: example comment
-- create table company (
--     id int primary key auto_increment not null,
--     name varchar(50) not null,
--     address1 varchar(50),
--     address2 varchar(50),
--     city varchar(30)
-- )
-- --rollback DROP TABLE company;

-- --changeset other.dev:3 labels:example-label context:example-context
-- --comment: example comment
-- alter table person add column country varchar(2)
-- --rollback ALTER TABLE person DROP COLUMN country;


--Execution command: update --defaults-file=defaults.properties